### ISSUE TITLE
Slug names should only be alphanumeric.

### ISSUE THREAD

**Issue by surbas** [pointfreeco/pointfreeco#133]
Slug names should only be alphanumeric.

Hello. Great project. Love the site. Can't wait to subscribe. Was just sharing your link to the first episode in slack when a person wrote back that the link was broken.

"https://www.pointfree.co/episodes/ep1-we-launched!"

Turned out that the "!" wasn't interpreted by slack as apart of the url... this is probably really a problem for slack. (RFC 3986 said it should be supported in a URI), but IMHO it is against convention to have punctuation in slug and slack (and github apparently) not supporting it is case and point.

**Comment by stephencelis** [comment]
Thanks!
