### ISSUE TITLE
Subscribed user can't see pre-release version of episode 2

### ISSUE THREAD

**Issue by Killectro** [pointfreeco/pointfreeco#136]
I got an annual subscription with this Github username and I'm unable to play the pre-release version of episode 2. The play button is greyed out and has no effect.

<img width="616" alt="screen shot 2018-01-29 at 11 03 21 pm" src="https://user-images.githubusercontent.com/1429690/35547710-a74d7a7c-0548-11e8-9b98-26ca4a9a3854.png">

**Comment by stephencelis** [comment]
@Killectro Can you try in Safari as a workaround? We exported a WebM source but there may have been a transcoding issue. We'll look into this soon!

**Comment by stephencelis** [comment]
(Thanks for the report! And thanks for subscribing!!)

**Comment by Killectro** [comment]
Confirmed that Safari works! You would think that as a programmer I would write better bugs. I was originally running Chrome version `63.0.3239.132`.

Thanks to both of you, looking forward to the rest of the series!

**Comment by stephencelis** [comment]
Great! Thanks for checking!

We'll get this fixed for Chrome tomorrow. It's been a long day in New York :) Hope you enjoy!

**Comment by stephencelis** [comment]
🤦‍♂️ Forgot to publish the WebM stream! Would you please check again in Chrome when you have the chance and let us know if it's been resolved for you?

**Comment by Killectro** [comment]
Yup looks fixed!

**Comment by stephencelis** [comment]
Thanks!

**Comment by mbrandonw** [comment]
@Killectro @stephencelis oops, forgot to mark the finished transcoded file as public. now done!
