### ISSUE TITLE
Feature Request: RSS Feed

### ISSUE THREAD

**Issue by mergesort** [pointfreeco/pointfreeco#146]
I'd love to be able to subscribe to the videos in my RSS reader, so I can keep up with the episodes.

I'm currently just watching the free videos if that makes a difference, and the pro tier does offer that.

Thanks a lot!

**Comment by stephencelis** [comment]
We've actually got an Atom feed! If you paste our homepage into Reeder or Feedbin it should find the meta tag, otherwise:

https://www.pointfree.co/feed/atom.xml

Right now it's just a blurb and link to the page. Is that what you mean?

**Comment by mergesort** [comment]
That worked for me!

I didn't know Feedbin could do that, I spend most of my time trying all the combos of `/rss`, `/index.rss`, etc. Didn't think to try `/feed/atom.xml`, but that's not your problem. 🙂

Closing this out now that it's solved, thanks!
