### ISSUE TITLE
Issue running playgrounds locally

### ISSUE THREAD

**Issue by urban** [pointfreeco/pointfreeco#181]
First of all, I really love the work you guys are doing to help everyone learn FP concepts in Swift. It's been immensely helpful.

In order to better understand what, why and how you are writing software. I'm able to run the server locally using `make bootstrap-oss` and `make run-oss` however however I've run into one issue when trying to build the server in xCode so I can see how you are using playground-driven development for the view layer.

I get the following error when trying to build the server in xCode (On line 40 of `main.swf`).

```
AppEnvironment.push(\.episodes .~ allEpisodes) // Use of unresolved identifier 'allEpisodes'
```

How can I resolve this so I can play with the playgrounds implementation?

Thanks!

**Comment by mbrandonw** [comment]
Oh, good catch. That `allEpisodes` value comes from our private transcripts directory. We provide a "stub" episode called `typeSafeHtml`, so you should be able to just do:

```swift
AppEnvironment.push(\.episodes .~ [typeSafeHtml])
```

to get that working. Can you let me know if that works, and if so we can try to make the OSS code a lil more resilient. 

Thanks!

**Comment by urban** [comment]
Thanks for quick reply but unfortunately, replacing the offending line with the one you provided gives me the following compiler error.

```
pointfreeco/Sources/Server/main.swift:40:21: Type of expression is ambiguous without more context
```

Thanks!

**Comment by mbrandonw** [comment]
@urban oh sorry, I should have tested locally. I meant 

```swift
AppEnvironment.push(\.episodes .~ { [typeSafeHtml] })
```

The `allEpisodes` value is a function that returns an array... oops!

**Comment by mbrandonw** [comment]
Hey @urban, can you let me know if that works for you and I can make this change for everyone running the OSS code?

**Comment by urban** [comment]
Hey @mbrandonw. With the change above, I was able to build the project however when I try to run `About` playground page to see the Live View, I get the following error in the console.

```
Playground execution failed:

error: pointfreeco.playground:2:18: error: missing required module 'Ccmark'
@testable import PointFree
```

**Comment by mbrandonw** [comment]
Ok great! Getting closer. I can make that change for OSS people.

For your newest problem, it looks like there's yet another modulemap that we need to install that we didn't include in the bootstrap :/ I'll get that running later today. Wish playgrounds could discover these dependencies more easily!

**Comment by mbrandonw** [comment]
Oops, this shouldn't have closed.

@urban so with #183 merged I believe you can now run `make ccmark-mm` to install the ccmark module map into your system frameworks. This requires sudo access so you may want to look at what the makefile is doing:

https://github.com/pointfreeco/pointfreeco/blob/master/Makefile#L147-L149

I'm hoping this fixes it!

**Comment by urban** [comment]
First, thank for all your help with this. I really appreciate you even making an open source version to run locally and I know it can't be easy keeping the two forks in sync.

I feel like we're getting very close however I am still running into and issue. After running `make ccmark-mm`, `make bootstrap-oss` and building the server in Xcode, when I try to view the About playground page, I get the following error in the console.

```
Playground execution failed:

error: pointfreeco.playground:12:56: error: missing argument label 'expand:' in call
let request = PointFreeTestSupport.request(to: .pricing(nil, nil))
                                                       ^
                                                             expand: 
```

I changed the request line to:

```
let request = PointFreeTestSupport.request(to: .pricing(nil, expand: nil))
```

After making that change, I get a cryptic error in console. I've omitted the some of the message for brevity (replaced with `...`)

```
dyld: lazy symbol binding failed: Symbol not found:
    ...
dyld: Symbol not found:
    ...
```

I wish I knew more about Swift and the iOS development ecosystem to help trouble shoot this myself but I'm new and still leanring.

Thanks again!

**Comment by stephencelis** [comment]
Can you replace the `...` with the full message? We should be able to take the symbol names there to better troubleshoot what's goin on

**Comment by mbrandonw** [comment]
@urban oh you know what, can you make sure you are build the `PointFree-Package` target?

<img width="310" alt="screenshot 2018-03-16 16 51 42" src="https://user-images.githubusercontent.com/135203/37544131-5bbb4650-293a-11e8-8909-9847e48bda73.png">

That builds _all_ of the dependencies. 

We recently merged two repos into one and it seems there's a few rough edges we need to soften.

**Comment by urban** [comment]
I had it building the `Server` but after changing it to `PointFree-Package` it now works! Thanks for the all the help.

**Comment by mbrandonw** [comment]
Woooooo!

Sounds like Stephen and me need to make the bootstrap process a lil better.

Thanks for helping us with that!
