### ISSUE TITLE
[Bug] Space key for video playback pause/continue is not functioning correctly

### ISSUE THREAD

**Issue by axl411** [pointfreeco/pointfreeco#182]
This is related to https://github.com/pointfreeco/pointfreeco/issues/173

Browser: Chrome

Expected behavior:
- Pressing the space key toggles video playback pause/continue

Actual behavior:
- Pressing down the space key (before finger up) toggles pause/continue once
- Finger up, another pause/continue is toggled. So 2 toggles happen for a single pressing down & finger up and the latter toggle just cancels the former toggle.

**Comment by stephencelis** [comment]
Ah, ya know what, the last-minute change made things more accessible but broke Chrome. I was mainly testing in Safari. Will try to get a fix out soon!
