### ISSUE TITLE
Bootstrap-oss error

### ISSUE THREAD

**Issue by eliotfowler** [pointfreeco/pointfreeco#232]
I am trying to get the pointfree code running locally and I ran into an issue while trying to boostrap.

```
❯ make bootstrap-oss
test -f .env \
		|| cp .env.example .env
test -d Sources/Server/Transcripts/ \
		|| cp -r Transcripts.example/ Sources/Server/Transcripts/
cp: directory Sources/Server/Transcripts does not exist
make: *** [mock-transcripts] Error 1
```

I see that the git submodule for episode-transcripts lives inside Sources/Pointfree, but since that's done in bootstrap-common, it happens after the mock-transcripts task attempts to copy. I tried running `git submodule update --init --recursive` which is when I realized that it appears the [episode-transcripts](https://github.com/mbrandonw/episode-transcripts/tree/6260c6bcaf7e3a959bad435305888e92a156d762) repo is no longer public (or no longer exists). 

It's very likely I messed something up on my end. It's not urgent but I'd really appreciate a push in the right direction!

**Comment by mbrandonw** [comment]
Looks like in some of our most recent work to clean things up (#229) we forgot to update the bootstrap! We'll have a fix shortly...

**Comment by garricn** [comment]
I was going to report this last night but I thought maybe I was just doing something wrong! I saw Steven’s commit but still just thought I was missing something 🙈

**Comment by mbrandonw** [comment]
This should be fixed by https://github.com/pointfreeco/pointfreeco/pull/233 !

Gotta step out for a bit, but when y'all get a moment give it a shot!

**Comment by eliotfowler** [comment]
Confirmed fixed for me!
