### ISSUE TITLE
Running playgrounds

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [pointfreeco/pointfreeco#249]
Firstly nice work guys. 

When building pointfreePackageDistribution I get the following issue:

Showing Recent Messages
unable to open dependencies file (...Developer/Xcode/DerivedData/PointFree-ghgmnwhqpbnvtibcslwnkunerblt/Build/Intermediates.noindex/PointFree.build/Debug/PointFreePackageDescription.build/Objects-normal/x86_64/PointFreePackageDescription_dependency_info.dat)

**Comment by stephencelis** [comment]
Hey there! The project file that SwiftPM generates is a little confusing. Those “package description” targets aren’t what you want to build. Try “PointFree-Package” and let us know if that gets you situated!

**Comment by TYRONEMICHAEL** [comment]
Thanks @stephencelis . I was able to build the scheme successfully. When running playgrounds I get the following inside the playground files:

```
error: missing required module 'CNIOAtomics'
```

I am going to investigate further. Feel free to close this if it is only me having this issue.

**Comment by nicnieumiem** [comment]
Hi guys, first of all - great and very inspiring work.

I'm also having the 
`error: missing required module 'CNIOAtomics'` 
issue while trying to execute playgrounds.

**Comment by stephencelis** [comment]
Hm, we may have an order of operations issue with our Makefile. If you run `make bootstrap` a second time does that get you situated? Can you outline the steps you’ve taken so far?

**Comment by TYRONEMICHAEL** [comment]
@stephencelis  running `make bootstrap-oss` sorts it out for me.

**Comment by stephencelis** [comment]
Closed by #251.
