### ISSUE TITLE
Duration of video

### ISSUE THREAD

**Issue by anil-chopra** [pointfreeco/pointfreeco#274]
It would be great to have video duration shown some where.

For example
<img width="786" alt="screen shot 2018-07-09 at 12 07 46 am" src="https://user-images.githubusercontent.com/24710791/42422845-2683b158-830c-11e8-8b34-afa8471012fa.png">

**Comment by mbrandonw** [comment]
very good feedback! we'll definitely take this into serious consideration...

**Comment by mbrandonw** [comment]
Hey Anil, thanks again for the great feature request. We just deployed some code that implements this!

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/135203/42768860-90abb7b4-88ee-11e8-8b51-e02ed67cada4.png">
