### ISSUE TITLE
make command error

### ISSUE THREAD

**Issue by alirp88** [pointfreeco/pointfreeco#286]
Hey,

I just following your video about "A Tour of Point-Free" and so I cloned the repo and then when I wanted to run `make` I faced the following error

```
/Library/Ruby/Gems/2.3.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
	from /usr/local/bin/make:22:in `load'
	from /usr/local/bin/make:22:in `<main>'
```

**Comment by stephencelis** [comment]
Hey @alirp88! Looks like you have a RubyGem called `make` installed, which has hijacked the system-level `make` command? Or are you running the command in a Ruby console?

You should be able to workaround by invoking the default `make` command:

``` sh
/usr/bin/make
```

You might wanna look into why you have that gem installed, though!

**Comment by alirp88** [comment]
tnx for the hint I will why that gem installed on my device,
