### ISSUE TITLE
Unable to enter 10...19 for team size

### ISSUE THREAD

**Issue by marksands** [pointfreeco/pointfreeco#292]
On the "For your team" input field at https://www.pointfree.co/pricing, I am unable to enter a number in the tens (I am trying to enter `14`). A few seconds of searching the source code brought me here https://github.com/pointfreeco/pointfreeco/blob/master/Sources/PointFree/Pricing.swift#L431 which looks like it might be trying to clamp my `1` between the valid range changing it to a `2`.

For anyone else having the same trouble, I can work around this by entering a `4` and then moving the cursor to the beginning and prepending a `1` to make `14.

**Comment by stephencelis** [comment]
Ha, serves me right for writing untyped JavaScript! Are you able to use the arrows on the number field as a workaround?

**Comment by marksands** [comment]
Ah, yep! The arrow keys also work. 😊
