### ISSUE TITLE
Resume videos where you left off

### ISSUE THREAD

**Issue by jasonzurita** [pointfreeco/pointfreeco#318]
If you leave a video unfinished, that video should return back to the spot where you left off.

**For example**:
- Start video (~30min video)
- Close browser after 10 minutes of watching
- Open browser and go back to video (doesn't have to be same day)
- Video should be ready to play from the 10 minute mark where you left off

**Possible solutions**:
- Local storage
  + potentially less complicated to implement
- Server storage
  + potentially more complicated to implement
  + benefit of doing this is that you can be more granular in your tracking (e.g. log when a user watches and for how long), which could help give insight into user behavior.
  + synchronized watching across devices

**Comment by jasonzurita** [comment]
Depending on the complexity, I would be interested in taking a stab at this one.

**Comment by mbrandonw** [comment]
I really like this idea, and we're totally down for you to give it a stab if you want, and help out where necessary. We could also use this work to some day mark episodes as "watched", which is something we've wanted to do for awhile.

Over the next few days I'll outline a few tasks that could be accomplished to get this going. It'd be awesome if we could do it as a few tiny PR's that ultimately work towards the feature.

Thanks for the interest!

**Comment by jasonzurita** [comment]
I have been wanting a "watched" too! Seems like this effort could have a larger impact if it also lays the ground work for the "watched" feature.

I like the idea of smaller PRs. I look forward to your outline :).

**Comment by mbrandonw** [comment]
oh we actually implemented this recently, so gonna close this!
