### ISSUE TITLE
Additional playback speeds

### ISSUE THREAD

**Issue by krzysztofzablocki** [pointfreeco/pointfreeco#354]
Right now we can change the playback speed by increments of 0.5x, but in many platform the usual increase is 0.25x and the difference here is quite significant for those of us that like to watch at increased speed, any chance we could support that?

**Comment by mbrandonw** [comment]
Good point! I just opened #356, will merge and deploy soon. Thanks!

**Comment by mbrandonw** [comment]
Done, thanks for the suggestion!
