### ISSUE TITLE
Problem about BackwardsComposition associativity in episode 6

### ISSUE THREAD

**Issue by Arcovv** [pointfreeco/pointfreeco#381]
In episode 6, we saw the new operator `BackwardsComposition` at 09:56 timeline. In the video, we could see the associativity about this operator said `associativity: left`. 

But in the transcript (https://www.pointfree.co/episodes/ep6-functional-setters#t545) wrote `associativity: right`.

I also check this operator in https://github.com/pointfreeco/swift-prelude/blob/master/Sources/Prelude/Operators.swift#L6, and the associativity is right in https://github.com/pointfreeco/swift-prelude/blob/master/Sources/Prelude/PrecedenceGroups.swift#L80.

So I think we should add `Video Correction` block in this transcript.

**Comment by stephencelis** [comment]
Hi @Arcovv! Nice catch! I've updated the transcript to match the video and am deploying the change now.

Luckily function composition is fully associative (`f <<< (g <<< h) = (f <<< g) <<< h`), so the direction of the associativity doesn't matter: the end result will behave the same. In the episode we just reached for the first direction we thought of, and in Prelude we copied from Haskell's precedence groups. Haskell seems to have picked "right" for a reason that doesn't seem to affect us in Swift: https://stackoverflow.com/questions/20342860/why-is-function-composition-in-haskell-right-associative

So in this case I don't think a correction block is necessary, but the code sample should definitely match what you see on the screen!
