### ISSUE TITLE
0002-SideEffects EffectfulComposition precedence group compiler error

### ISSUE THREAD

**Issue by ksm** [pointfreeco/pointfreeco#430]
Just playing in Xcode Playgrounds with episodes 0001 and 0002. Having all the operators and precedencegroups in one file leads to the error below. Moving ForwardApplication and ForwardComposition off to a Playgrounds Sources Util file (just like in https://github.com/pointfreeco/episode-code-samples/tree/master/0002-side-effects) fixes the issue.

<img width="1364" alt="Screen Shot 2019-04-02 at 1 35 10 PM" src="https://user-images.githubusercontent.com/747910/55424090-76791400-554d-11e9-847a-6c5075159a1c.png">

So I guess this is not really such a big issue, but more of a "hey this might throw people off that are working away at their functional programming in one giant playground".

**Comment by ksm** [comment]
Closing, but may be of interest.

**Comment by stephencelis** [comment]
We've seen folks have a bit of trouble with this before. Something to keep in mind for sure.
