### ISSUE TITLE
Wrong log level value for destination selection

### ISSUE THREAD

**Issue by bradhowes** [pointfreeco/pointfreeco#437]
I _think_ that the following line should refer to the local `level` value and not `self.level`:

https://github.com/pointfreeco/pointfreeco/blob/e15a51cf73fd486c6f2cc5f9d5d1e86189333cd7/Sources/Logger/Logger.swift#L48

Right now, all log lines will go to the same destination (based on the level given in the constructor), regardless of the level of the message.

**Comment by mbrandonw** [comment]
Ah yes, I think you're right!

just to double check: @stephencelis that seem right to you?

**Comment by stephencelis** [comment]
I think so! Also in the print statements.
