### ISSUE TITLE
Typos in transcript of ep63

### ISSUE THREAD

**Issue by konrad1977** [pointfreeco/pointfreeco#542]
In ep63 there is a typo in the code. 

1. If with a capital I
2. ' If s.run(&str) == nil else {' is not valid Swiftcode. Should probably be if s.run(&str) != nil { ... } 

<img width="532" alt="Skärmavbild 2020-01-11 kl  11 18 50" src="https://user-images.githubusercontent.com/4384932/72202838-5d01e280-3464-11ea-8776-166911cbe08d.png">

**Comment by stephencelis** [comment]
Thanks for letting us know! We've made the fix and a deploy will go out shortly!
