### ISSUE TITLE
Ep63: Swift code parser (Html block) doesn't handle escaped strings correctly.

### ISSUE THREAD

**Issue by konrad1977** [pointfreeco/pointfreeco#543]
The second check should be `$0 == "\n"` but the browser seems to think its a new line. 
I usually dont read the subscript that often, so it might appear in more places.

<img width="425" alt="Skärmavbild 2020-01-11 kl  11 25 10" src="https://user-images.githubusercontent.com/4384932/72202906-1496f480-3465-11ea-8c18-99f940c5e078.png">

**Comment by stephencelis** [comment]
Thanks again! This fix will go out with the next deploy. 😄
