### ISSUE TITLE
Wrapping should be enabled on markdown code blocks?

### ISSUE THREAD

**Issue by huynguyen** [pointfreeco/pointfreeco#638]
Not sure if this was intentional or not from [this change](https://github.com/pointfreeco/pointfreeco/blame/ce93ea07bc5a1b62639a93be3cdf246219257a4b/Sources/Views/Markdown.swift#L65), but the code blocks inside the Solutions sections of exercises are really hard to read when `white-space: nowrap` is applied on them.

Current:
![pf-codeblock-nowrap](https://user-images.githubusercontent.com/470767/77015803-27311c80-6933-11ea-8a1d-7faed121f716.gif)

Disabled:
![pf-codeblock-wrapped](https://user-images.githubusercontent.com/470767/77015856-52b40700-6933-11ea-9b17-cda42d682898.png)

**Comment by mbrandonw** [comment]
Ah yes, good find! That was a mistake on our part. We have a PR here https://github.com/pointfreeco/pointfreeco/pull/639 that we will deploy soon
