### ISSUE TITLE
Trouble running Playgrounds

### ISSUE THREAD

**Issue by tapcast-kevin** [pointfreeco/pointfreeco#652]
I've successfully bootstrapped and I'm able to run the server without any issues. However, I can't get any of the playground files to run.

I open the project via:

```bash
xed .
```

I switch to the PointFree-Package target and that builds find. However, when I try to run a playground page (Homepage, for example), I get a warning that the playground did not compile successfully.

![image](https://user-images.githubusercontent.com/55557894/80551144-5d70ab80-8977-11ea-9750-04cc3eab3c47.png)

I don't see any errors in the editor, but there are a number of errors in the console ([errors.txt](https://github.com/pointfreeco/pointfreeco/files/4549237/errors.txt)).

Would you kindly let me know what I'm doing wrong here?

Thanks!

**Comment by stephencelis** [comment]
Sorry about the delay!

Playgrounds (and Xcode previews) unfortunately aren't supported in SPM modules yet, so in order for playgrounds to work one needs to generate an Xcode project. We're hoping Apple gives us this functionality soon, though!

**Comment by tapcast-kevin** [comment]
No worries. I know you've been hard at work on TCA :)

Thanks for the update. At least I missing something obvious.
