### ISSUE TITLE
Incorrect order for catchToEffect and map 

### ISSUE THREAD

**Issue by xHunter** [pointfreeco/pointfreeco#659]
Map to `AppAction.numberFactResponse` should be after the `catchToEffect`

https://github.com/pointfreeco/pointfreeco/blob/6b4b1ee4d7341528b7d7bfea05152522e2d63655/Sources/Models/BlogPosts/BlogPost0041_AnnouncingTheComposableArchitecture.swift#L87-L91

**Comment by stephencelis** [comment]
Good catch! Fixed and will deploy in a bit.
