### ISSUE TITLE
Atom feed for blog doesn’t work (in Feedly)

### ISSUE THREAD

**Issue by ole** [pointfreeco/pointfreeco#711]
I noticed via https://github.com/pointfreeco/swift-composable-architecture/discussions/658 that your Atom feed at https://www.pointfree.co/blog/feed/atom.xml doesn’t seem to be working for me in [Feedly](https://feedly.com/). Here’s a screenshot showing that Feedly hasn’t updated your feed since December 2019:

<img width="974" alt="Screen Shot 2021-07-15 at 11 39 32" src="https://user-images.githubusercontent.com/5010/125766995-201f10df-3ead-4f04-a673-fb98bb07bad0.png">

Looking at the source of the feed, I noticed that the entries seems to be sorted by publish date in _ascending_ order, whereas most systems seem to be sorting in the reverse order (newest post first). I don’t know if this trips up Feedly, though.

[I ran the feed through a feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.pointfree.co%2Fblog%2Ffeed%2Fatom.xml) and got this error message:

> Error -3 while decompressing data: invalid stored block lengths (Server response declares Content-Encoding: deflate; misconfigured server?)

But I'm not sure this is relevant.

Pasting the feed’s contents into the validator also generates an error:

> This feed does not validate.
> 
>     line 27, column 33: XML parsing error: <unknown>:27:33: mismatched tag [help]
> 
>         </div></div></div>]]></content></entry><entry><title>Case Study: Algebraic D ...
>                                          ^
>

**Comment by mbrandonw** [comment]
Got a fix in #713, thanks for the heads up @ole!

**Comment by mbrandonw** [comment]
Oops, didn't mean to auto-close this with my PR.

But I believe this should be fixed now. W3C says it validates, but that there are some additional small improvements we could do to maximize interoperability.

**Comment by ole** [comment]
@mbrandonw Thanks! I can confirm that the feed shows up fine in Feedly:

<img width="794" alt="Screen Shot 2021-07-23 at 09 42 50" src="https://user-images.githubusercontent.com/5010/126751810-afc3cdbd-8850-44b6-8280-ecbb060d895f.png">
