### ISSUE TITLE
Source code needs formatted

### ISSUE THREAD

**Issue by kgrigsby59** [pointfreeco/pointfreeco#718]
I’m not sure if this is the correct repo for reporting issues about the website text.
On the page https://www.pointfree.co/collections/composable-architecture/adaptation/ep96-adaptive-state-management-actions at the 19:14 paragraph, the source code needs formatted.

**Comment by mbrandonw** [comment]
Good catch! I've just fixed those typos and I'm deploying now. Thanks for letting us know!
