### ISSUE TITLE
Building Package from fresh - errors

### ISSUE THREAD

**Issue by dndydon** [pointfreeco/pointfreeco#74]
Thumbs up on all of this...  just in case you don't know, a fresh run of your installation instructions results in these errors (at least for me.)

[PointFreeCo Build Errors.rtfd.zip](https://github.com/pointfreeco/pointfreeco/files/1590077/PointFreeCo.Build.Errors.rtfd.zip)

Thanks!

**Comment by stephencelis** [comment]
Ah! Yeah we haven't updated since we got database stuff going. Getting up-and-running may be as simple as installing PostgreSQL (via `brew install postgres`), though we'll have to take a deeper look soon.

**Comment by stephencelis** [comment]
Please follow our updated instructions and let us know if you still have issues building! Thanks again for the report!
