### ISSUE TITLE
Code Snippet Error in Ep 213

### ISSUE THREAD

**Issue by JCSooHwanCho** [pointfreeco/pointfreeco#790]
in 44:01, 'letter' is defined in Destination enum.

but after that, this case is referred as 'text'.

and in  44:31 snippet has error, I think. 

```swift
  for destination in self.path {
    switch destination {
    case let .counter(model):
      sum += model.count
    case .text:
      break // this line must be continue.
    }
  }
```

**Comment by JCSooHwanCho** [comment]
+ addition

in 48:42, delegate closures are implemented just empty closure. but in 52:16, it says we will get instant notification. Should it be 'unimplemted'?

**Comment by JCSooHwanCho** [comment]
- addition2
in 52:53, Defined case is text. But in 54:36, the letter case is used.

**Comment by stephencelis** [comment]
Fixed, thanks! Will go out with the next deploy.
