### ISSUE TITLE
Invalid/expired Slack url

### ISSUE THREAD

**Issue by JacksonUtsch** [pointfreeco/pointfreeco#824]
Slack [invite link](https://github.com/pointfreeco/pointfreeco/blob/eb7a5f5bd6f5f8f1f6fb3327ee80bfd48660e82c/Sources/Models/BlogPosts/BlogPost0100_Anniversary.swift#L73) is broken!

**Comment by mbrandonw** [comment]
Hi @JacksonUtsch, yeah we didn't realize those Slack links expire. We are deploying an update to the blog, but for now you can use this:

https://join.slack.com/t/pointfreecommunity/shared_invite/zt-1o8l02r36-lygnfRjdoCZA3GtpG9bo_Q

**Comment by mbrandonw** [comment]
This is now fixed, thanks for the heads up!
