### ISSUE TITLE
Missing transcription for Episode 2: side-effects

### ISSUE THREAD

**Issue by devioustree** [pointfreeco/pointfreeco#835]
The transcription for [episode 2](https://www.pointfree.co/episodes/ep2-side-effects) is currently empty. I think this happened when [migrating the transcriptions to markdown](https://github.com/pointfreeco/pointfreeco/blob/88aa184cc207f2eecda9dcaaaba16901a4433eab/Sources/Transcripts/Episodes/0002-SideEffects.swift#L34)

**Comment by mbrandonw** [comment]
Oops, good catch! I just pushed a fix d5e0428e, thanks! Deploy is going out now.
