### ISSUE TITLE
insecure use of `collect(upTo: contentLength)`

### ISSUE THREAD

**Issue by weissi** [pointfreeco/pointfreeco#911]
https://github.com/pointfreeco/pointfreeco/blob/b08d363e347ab8b984dbc5f3d922e0c0866c7e44/Sources/FoundationPrelude/AsyncHTTPClient.swift#L62

This line should be fixed to use a fixed limit. Setting it to `contentLength` doesn't make sense as that'd be the same as "limiting" it by `Int.max` (because the `content-length` header is fully in control of a potential attacker on the other side). If that's desired (unlikely as that would open it up to denial of service attacks), then I'd recommend to be explicit: `collect(upTo: Int.max)`.

But really: This should be a fixed number (maybe 16 MiB) of the maximum amount of bytes you're willing to balloon into memory here.

---

Please note that you do not need to validate (or even read) the `content-length` header, AsyncHTTPClient and SwiftNIO validate that it's correct (if present at all).

**Comment by stephencelis** [comment]
Thanks! We only use this code as a GitHub API client, but better to be safe than sorry :)
